% >> Aura2eeglab()
% Usage: Aura2eeglab("samples.csv")
%
%  Inputs: 
%     filename:        - Name of the file generated by AURA EEG acquisition
%                        software.
%__________________________________________________________________________
%
%   This function converts a file generated by AURA EEG acquisition
%   software to the standard EEG struct accepted by EEGLAB. 
%
%   This function requires:
%       - eeglab
%       - eeg_emptyset.m
%__________________________________________________________________________
%
% by: Diego Caro López, Mirai Innovation Research Institute, 
%     EMFUTECH Fall 2025, Osaka, Japan. 
%     15-Oct-2025.

function EEG = Aura2eeglab(filename)
    raw = readtable(filename,'VariableNamingRule','preserve');
    raw(:,[1,10:16]) = [];
    chans = raw(:,1:end-1).Properties.VariableNames;
    chans = cellfun(@(x) x(2:end-1),chans,'UniformOutput',false);
    events = raw(:,9);
    raw(:,9) = [];

    fs = 250;
    EEG = eeg_emptyset;
    EEG.data = table2array(raw)';
    EEG.pnts = size(EEG.data,2);
    EEG.xmin = 0;
    EEG.xmax = (EEG.pnts-1)/fs;
    EEG.nbchan = size(EEG.data,1);
    EEG.chanlocs = struct('labels',chans);
    EEG.times = 1:size(EEG.data,2);
    EEG.trials = 1;
    EEG.srate = fs;
    EEG.events_dcaro = table2array(events)';
end
